version: '3.8'

services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5678:5678"
    environment:
      # Variáveis para o n8n funcionar localmente
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=development
      # Variáveis que o script Python precisa, lidas do arquivo .env
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
    # Este volume garante que seus workflows e credenciais do n8n local persistam
